export const LIST_SEARCH_RESULTS = 'LIST_SEARCH_RESULTS';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SET_COLLECTION = 'SET_COLLECTION';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
